### ISSUE TITLE
Kratios: Approval Voting + CSV

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/ui-components#20]
As Vocdoni we want to validate the Approval voting type using the SDK by:

**Approval Voting:**

- [x]  Create the approval voting with it's params
- [ ]  Verify the UI-components and needed changes
- [ ]  Test the voting flow and results

**CSV:**
- [ ]  Add an example in the UI-components on how a CSV file should work

**Comment by emmdim** [comment]
@elboletaire  well yes and no. It would make sense to be another flavour of ui-components.
My reasoning is the following:
The idea is that the integrator would need to do some developing. Therefore I would like to provide a clean template.
On the other hand this will not serve for the future, since Approval voting should be implemented in the SDK or even th backend.
