### ISSUE TITLE
Allow setting custom URLs to clients

### ISSUE THREAD

**Issue by selankon** [vocdoni/ui-components#87]
The census 3 have an attribute called api-url to point the census3 service, which on the react providers, cannot be changed.

**Comment by elboletaire** [comment]
I think this should be a more generic issue, and also ensure setting custom urls in the client works. Right now I'm pretty sure it won't work in some scenarios, and should be checked and fixed.

I'm changing the title.

**Comment by elboletaire** [comment]
Due to how the `env` and `api_url` settings work, there's a clash in some scenarios that could be resolved by storing the first defined `api_url` via the provider (when a client is specified, ofc). But after speaking with Marc, we considered this can wait until the SDK refactoring of this part is done (see vocdoni/vocdoni-sdk/issues/243).

**Comment by elboletaire** [comment]
closed by #118

**Comment by elboletaire** [comment]
Dang, we did forgot about the census3 options 🤦🏼
